- type: entity
  name: cleanades box
  parent: BoxCardboard
  id: BoxCleanerGrenades
  description: A box full of cleanades.
  components:
  - type: StorageFill
    contents:
      - id: CleanerGrenade
        amount: 4
  - type: Sprite
    layers:
# Start of Harmony Change: Updates Cleanade Box Sprite States
#      - state: box
#      - state: flashbang
      - state: box_janitorial
      - state: cleanade
# End of Harmony Change

- type: entity
  name: NT "AgriChem Is Fun" kit
  parent: BoxCardboard
  id: BoxAgrichem
  description: For the budding botanist ready to learn about maximizing farm output. This faded box must be at least 50 years old.
  components:
  - type: StorageFill
    contents:
    - id: PaperAgrichemManual
    - id: ChemistryEmptyBottle01
    - id: ChemistryBottlePotassium
    - id: ChemistryBottlePhosphorus
    - id: ChemistryBottleNitrogen
    - id: ChemistryBottleHydrogen
    - id: ChemistryBottleEthanol
    - id: RadiumChemistryVial
    - id: ChlorineChemistryVial
  - type: Sprite
    layers:
      - state: boxwide
      - state: agrichemkit
  - type: GuideHelp
    guides:
    - Botanical
    - Chemicals
